### Question 1. 


Write a script to return the standard deviation of a portion of a 2-D array, specified by the
user, from a text file of floating point numbers, also specified by the user. Make your own text
file of numbers with your favourite text editor, and verify that it works.

In [10]:
#Your code with answer

### Question 2. 
Write a script to read in a file and return an array which contains the index of all fields which could contain a date between 1900 and 2020, e.g.
> Although solar eclipses (Alpha et al. 1980) might be granular
(Bethe & Gamow 2000), it is thought...

would return an array [6,13].

In [11]:
#Your code with answer

### Question 3.
A simple version of the FIRST catalogue (Becker et al. 1995, a catalogue of radio sources at
20cm made with the VLA) can be found on github page [Part_of_FIRST_catalog_14dec17.csv](https://github.com/sagar-sethi/PAO2_2022_python). Its columns for each source are: right ascension, declination, peak flux, total flux, major axis of fitted component (in arcseconds), minor axis (if the component is resolved, otherwise this field is 0.0), and component position angle.

> From the FIRST catalogue, print out a list of the right ascension and declination (both in
degrees) of all sources which have peak flux density of 100mJy or more. Append a ’C’ to those
sources which are not resolved.

In [12]:
#Your code with answer

### Question 4. 
Make a n×2 rray of RA and declination (in degrees) of all FIRST sources with total flux
density >100mJy. Find the two >100mJy sources with the smallest separation in declination.

In [13]:
#Your code with answer

### Question 5.
Make a 2-D image (like a numpy array) full of empty sky, whose size and counts per pixel can be specified by the
user. The noise in each pixel should be the square root of the number of counts.

In [9]:
#Your code with answer

### Question 6.
Make a 2-D image whose values at each pixel are the distance from a pixel which is specified by
the user. Then make a 2-D image which contains a Gaussian with a user-specified width, centre
(in pixels) and peak flux.

In [ ]:
#Your code with answer

### Question 7.

Write a function that reads data from a CSV file and calculates its mean and the median. Your function should take the name of the file as an argument and return the mean and median in a tuple, rounded to one decimal place.
The .txt files are available in the directory.

Output as follows for 1st file (data.csv)

```
for file data.csv, mean = 11.1 and median = 11.4.
```

In [17]:
#Your code with answer

### Question 8.

Write a mean_datasets function that reads in a list of CSV files and returns an array of the mean of each cell in the data files.

The files each contain n rows and m columns, giving a total of n x m cells. The individual cells are separated by commas, and all CSV files in the list will have the same number of rows and columns.

The result should have the same dimensions as the input files. The result should be a NumPy array with individual entries rounded to one decimal place.

Suppose we want to use the three files data1.csv, data2.csv and data3.csv. Your function should then take a list of the filenames and return the following:
```
data1.csv
7.98631,16.82952,19.65165
7.14460,10.41674,3.81853
7.48549,14.61958,8.87193
8.66521,14.14244,10.10248
14.80968,12.82048,13.41792

data2.csv
12.65900,13.22477,8.94481
7.11298,1.99820,8.49168
0.25181,9.79979,13.62024
1.98336,1.42358,9.92036
16.99241,18.93915,7.46266

data3.csv
12.47115,5.51385,10.31595
14.12714,8.03384,15.76423
13.78446,8.92194,15.08250
15.79836,6.28136,7.43691
17.93699,0.01700,10.15189

Test your code
mean_datasets(['data1.csv', 'data2.csv', 'data3.csv'])
array([[ 11.   11.9  13. ]
       [  9.5   6.8   9.4]
       [  7.2  11.1  12.5]
       [  8.8   7.3   9.2]
       [ 16.6  10.6  10.3]])
```

In [ ]:
#Your code with answer